In [79]:
import seaborn as sns
import matplotlib as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score

In [80]:
data = pd.read_csv(r'C:\Users\sheet\Desktop\Full Stack Data Science\Sep 30th Class notes\car-mpg.csv')

In [81]:
data

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,1,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,1,chevy s-10

In [82]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    str
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car_type  398 non-null    int64
 9   car_name  398 non-null    str
dtypes: float64(3), int64(5), str(2)
memory usage: 38.4 KB

In [83]:
data.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [84]:
data.head

<bound method NDFrame.head of       mpg  cyl   disp   hp    wt   acc  yr  origin  car_type  \
0    18.0    8  307.0  130  3504  12.0  70       1         0
1    15.0    8  350.0  165  3693  11.5  70       1         0
2    18.0    8  318.0  150  3436  11.0  70       1         0
3    16.0    8  304.0  150  3433  12.0  70       1         0
4    17.0    8  302.0  140  3449  10.5  70       1         0
..    ...  ...    ...  ...   ...   ...  ..     ...       ...
393  27.0    4  140.0   86  2790  15.6  82       1         1
394  44.0    4   97.0   52  2130  24.6  82       2         1
395  32.0    4  135.0   84  2295  11.6  82       1         1
396  28.0    4  120.0   79  2625  18.6  82       1         1
397  31.0    4  119.0   82  2720  19.4  82       1         1

                      car_name
0    chevrolet chevelle malibu
1            buick skylark 320
2           plymouth satellite
3                amc rebel sst
4                  ford torino
..                         ...
393            ford mustang gl
394                  vw pickup
395              dodge rampage
396                ford ranger
397                 chevy s-10

[398 rows x 10 columns]>

In [85]:
data.shape

(398, 10)

In [86]:
data.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'origin', 'car_type',
       'car_name'],
      dtype='str')

In [87]:
data.head(1)

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu

In [88]:
data = data.drop(['car_name'], axis=1)

data['origin'] = data['origin'].replace({
    1: 'America',
    2: 'Europe',
    3: 'Asia'
})

data = pd.get_dummies(data, columns=['origin'], dtype=int)

import numpy as np

data = data.replace('?', np.nan)

data = data.apply(pd.to_numeric, errors='coerce')

# Fill median only for numeric columns
data = data.apply(
    lambda x: x.fillna(x.median()) if x.dtype != 'object' else x,
    axis=0
)

In [89]:
print(data.columns)

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'car_type',
       'origin_America', 'origin_Asia', 'origin_Europe'],
      dtype='str')

In [90]:
print(data.dtypes)

mpg               float64
cyl                 int64
disp              float64
hp                float64
wt                  int64
acc               float64
yr                  int64
car_type            int64
origin_America      int64
origin_Asia         int64
origin_Europe       int64
dtype: object

In [91]:
data

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_America,origin_Asia,origin_Europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140.0,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1,1,0,0
394,44.0,4,97.0,52.0,2130,24.6,82,1,0,0,1
395,32.0,4,135.0,84.0,2295,11.6,82,1,1,0,0
396,28.0,4,120.0,79.0,2625,18.6,82,1,1,0,0
397,31.0,4,119.0,82.0,2720,19.4,82,1,1,0,0

In [93]:
data.head(1)

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_America,origin_Asia,origin_Europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,1,0,0

In [95]:
x = data.drop(['mpg'], axis = 1)
y = data[['mpg']]

In [96]:
x.head(3)

,cyl,disp,hp,wt,acc,yr,car_type,origin_America,origin_Asia,origin_Europe
0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,8,318.0,150.0,3436,11.0,70,0,1,0,0

In [102]:
x_s = preprocessing.scale(x)

In [103]:
x_s

array([[ 1.49819126,  1.0906037 ,  0.67311762, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.5035143 ,  1.58995818, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.19623199,  1.19702651, ...,  0.77355903,
        -0.49764335, -0.46196822],
       ...,
       [-0.85632057, -0.56103873, -0.53187283, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.70507731, -0.66285006, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.71467988, -0.58426372, ...,  0.77355903,
        -0.49764335, -0.46196822]], shape=(398, 10))

In [104]:
y_s = preprocessing.scale(y)

In [105]:
y_s

array([[-7.06438701e-01],
       [-1.09075062e+00],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [ 6.21851453e-02],
       [-1.94022803e-01],
       [-7.06438701e-01],
       [-3.22126778e-01],
       [ 4.46497068e-01],
       [ 3.18393094e-01],
       [ 1.90289120e-01],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [ 3.18393094e-01],
       [-3.22126778e-01],
       [-1.73127050e+00],
       [-1.73127050e+00],
       [-1.60316652e+00],
       [-1.85937447e+00],
       [ 4.46497068e-01],
       [ 5.74601043e-01],
       [ 1.90289120e-01],
       [ 1.90289120e-01],
       [-5.78334726e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-7.06438701e-01],
       [-1.94022803e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-6.59188290e-02],
       [ 5.74601043e-01],
       [ 8.30808991e-01],
       [ 8.30808991e-01],
       [ 9.58912966e-01],
       [ 1.47132886e+00],
       [ 4.46497068e-01],
       [ 3.18393094e-01],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [-6.59188290e-02],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-8.34542675e-01],
       [-1.60316652e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-7.06438701e-01],
       [-1.94022803e-01],
       [-3.22126778e-01],
       [ 3.18393094e-01],
       [-1.94022803e-01],
       [ 5.74601043e-01],
       [-6.59188290e-02],
       [ 5.74601043e-01],
       [ 4.46497068e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-7.06438701e-01],
       [-7.06438701e-01],
       [-6.59188290e-02],
       [ 3.18393094e-01],
       [-1.60316652e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-7.06438701e-01],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-1.94022803e-01],
       [-7.06438701e-01],
       [-5.78334726e-01],
       [-3.22126778e-01],
       [ 3.18393094e-01],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [ 7.02705017e-01],
       [ 6.21851453e-02],
       [-4.50230752e-01],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [ 6.21851453e-02],
       [-4.50230752e-01],
       [-1.60316652e+00],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [ 9.58912966e-01],
       [ 3.18393094e-01],
       [ 1.08701694e+00],
       [ 1.90289120e-01],
       [-9.62646649e-01],
       [-9.62646649e-01],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [ 7.02705017e-01],
       [ 3.18393094e-01],
       [ 3.18393094e-01],
       [ 9.58912966e-01],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 6.21851453e-02],
       [ 3.18393094e-01],
       [ 6.21851453e-02],
       [ 3.18393094e-01],
       [ 9.58912966e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-1.09075062e+00],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [-1.21885460e+00],
       [-8.34542675e-01],
       [-9.62646649e-01],
       [-1.09075062e+00],
       [-7.06438701e-01],
       [-3.22126778e-01],
       [-4.50230752e-01],
       [-1.34695857e+00],
       [ 7.02705017e-01],
       [-6.59188290e-02],
       [-4.50230752e-01],
       [-6.59188290e-02],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [ 6.21851453e-02],
       [-7.06438701e-01],
       [ 7.02705017e-01],
       [-5.78334726e-01],
       [-6.59188290e-02],
       [-6.59188290e-02],
       [-1.94022803e-01],
       [ 1.90289120e-01],
       [ 1.21512091e+00],
       [ 5.74601043e-01],
       [ 1.90289120e-01],
       [ 1.90289120e-01],
       [ 3.18393094e-01],
       [ 4.46497068e-01],
       [-7.70490688e-01],
       [-9.62646649e-01],
       [-1.02669864e+00],
       [-1.15480261e+00],
       [-1.94022803e-01],
       [-1.94022803e-01],
       [ 6.21851453e-02],
       [-1.29970816e-01],
       [ 7.02705017e-01],
       [ 1.26237132e-01],
       [ 7.02705017e-01],
       [ 1.21512091e+00],
       [-4.50230752e-01],
       [-7.06438701e-01],
       [-6.42386713e-01],
       [-7.70490688e-01],
       [ 7.66757004e-01],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 3.82445081e-01],
       [-4.50230752e-01],
       [-1.34695857e+00],
       [-5.78334726e-01],
       [-5.78334726e-01],
       [-8.98594662e-01],
       [-8.98594662e-01],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [ 1.02296495e+00],
       [ 8.30808991e-01],
       [ 1.59943284e+00],
       [ 2.54341107e-01],
       [ 1.27917290e+00],
       [-7.70490688e-01],
       [-8.34542675e-01],
       [-1.02669864e+00],
       [-1.09075062e+00],
       [-7.70490688e-01],
       [-3.86178765e-01],
       [-5.78334726e-01],
       [-6.42386713e-01],
       [-9.62646649e-01],
       [-1.02669864e+00],
       [-1.02669864e+00],
       [-9.62646649e-01],
       [ 7.02705017e-01],
       [ 1.26237132e-01],
       [ 3.18393094e-01],
       [ 2.54341107e-01],
       [ 8.94860978e-01],
       [ 1.27917290e+00],
       [ 8.30808991e-01],
       [ 8.94860978e-01],
       [-1.94022803e-01],
       [-2.58074790e-01],
       [-2.58074790e-01],
       [ 2.50897106e+00],
       [ 1.61224323e+00],
       [ 1.18950012e+00],
       [ 2.03498635e+00],
       [ 1.61224323e+00],
       [-4.63041149e-01],
       [-5.27093137e-01],
       [-4.24609957e-01],
       [-5.52713931e-01],
       [-3.86178765e-01],
       [-4.24609957e-01],
       [ 2.03099517e-01],
       [-3.86178765e-01],
       [-5.27093137e-01],
       [-3.73368367e-01],
       [-3.47747573e-01],
       [-6.29576316e-01],
       [-6.93628303e-01],
       [-5.52713931e-01],
       [-7.44869893e-01],
       [-6.93628303e-01],
       [-7.70490688e-01],
       [ 8.30808991e-01],
       [ 5.10549055e-01],
       [ 4.72117863e-01],
       [ 9.46102568e-01],
       [-3.09316380e-01],
       [-4.02980341e-02],
       [ 3.65643505e-02],
       [ 4.93747479e-02],
       [-4.11799560e-01],
       [-8.34542675e-01],
       [-2.45264393e-01],
       [-9.37025854e-01],
       [ 1.02296495e+00],
       [ 7.66757004e-01],
       [-2.58074790e-01],
       [-4.75851547e-01],
       [-1.55591611e-01],
       [-4.24609957e-01],
       [-3.73368367e-01],
       [-8.34542675e-01],
       [-7.57680290e-01],
       [-8.98594662e-01],
       [-6.80817906e-01],
       [-8.47353072e-01],
       [-1.02669864e+00],
       [-5.52713931e-01],
       [-6.42386713e-01],
       [ 1.07420654e+00],
       [ 1.35603529e+00],
       [ 1.56100164e+00],
       [ 4.97738658e-01],
       [ 2.41530709e-01],
       [-6.59188290e-02],
       [ 4.72117863e-01],
       [ 4.93747479e-02],
       [ 1.36884568e+00],
       [ 1.40727688e+00],
       [ 1.06139615e+00],
       [ 1.76596800e+00],
       [ 6.25842632e-01],
       [ 6.77084222e-01],
       [ 4.20876273e-01],
       [ 1.27917290e+00],
       [ 2.30400470e+00],
       [ 1.86845118e+00],
       [ 1.09982734e+00],
       [ 1.75315761e+00],
       [ 5.74601043e-01],
       [ 3.69634684e-01],
       [ 1.00616338e-01],
       [-5.65524329e-01],
       [ 1.38165608e+00],
       [ 8.05188196e-01],
       [ 9.97344158e-01],
       [ 1.72753681e+00],
       [ 1.11263773e+00],
       [ 2.95733497e+00],
       [ 5.61790645e-01],
       [ 2.21433191e+00],
       [ 2.66269582e+00],
       [ 2.54740225e+00],
       [ 1.65067443e+00],
       [ 8.30808991e-01],
       [ 2.70112702e+00],
       [ 2.22714231e+00],
       [ 1.31760409e+00],
       [ 8.05188196e-01],
       [ 1.17668972e+00],
       [ 2.37539530e-02],
       [ 1.47132886e+00],
       [ 1.09435556e-02],
       [ 1.13825853e+00],
       [ 4.72117863e-01],
       [ 3.95255479e-01],
       [ 2.92772299e-01],
       [-1.86684184e-03],
       [ 8.30808991e-01],
       [ 1.99655516e+00],
       [ 1.98374476e+00],
       [ 1.48413926e+00],
       [ 1.12544813e+00],
       [ 1.72753681e+00],
       [ 1.81720959e+00],
       [ 1.35603529e+00],
       [ 1.43289767e+00],
       [ 1.39446648e+00],
       [ 8.17998594e-01],
       [ 1.21512091e+00],
       [ 1.40727688e+00],
       [ 1.30479370e+00],
       [ 1.13825853e+00],
       [ 1.20231052e+00],
       [ 1.03577535e+00],
       [ 5.87411440e-01],
       [ 9.20481773e-01],
       [ 2.41530709e-01],
       [ 8.78059402e-02],
       [-1.42781214e-01],
       [ 3.95255479e-01],
       [-4.24609957e-01],
       [-7.57680290e-01],
       [ 5.74601043e-01],
       [ 4.46497068e-01],
       [ 1.34322489e+00],
       [ 9.58912966e-01],
       [ 7.02705017e-01],
       [ 4.46497068e-01],
       [ 6.21851453e-02],
       [-6.59188290e-02],
       [ 1.59943284e+00],
       [ 1.72753681e+00],
       [ 9.58912966e-01],
       [ 1.85564079e+00],
       [ 1.59943284e+00],
       [ 1.59943284e+00],
       [ 1.59943284e+00],
       [ 1.34322489e+00],
       [ 1.85564079e+00],
       [ 1.08701694e+00],
       [ 1.85564079e+00],
       [ 1.90289120e-01],
       [ 1.85564079e+00],
       [ 3.18393094e-01],
       [-1.94022803e-01],
       [ 1.08701694e+00],
       [ 1.59943284e+00],
       [ 4.46497068e-01],
       [ 4.46497068e-01],
       [ 2.62426463e+00],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 9.58912966e-01]])

In [110]:
x_s = pd.DataFrame(x_s, columns=x.columns)
y_s = pd.DataFrame(y_s, columns=y.columns)

In [111]:
x_s

,cyl,disp,hp,wt,acc,yr,car_type,origin_America,origin_Asia,origin_Europe
0,1.498191,1.090604,0.673118,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.589958,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.197027,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.197027,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.935072,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
393,-0.856321,-0.513026,-0.479482,-0.213324,0.011586,1.621983,0.941412,0.773559,-0.497643,-0.461968
394,-0.856321,-0.925936,-1.370127,-0.993671,3.279296,1.621983,0.941412,-1.292726,-0.497643,2.164651
395,-0.856321,-0.561039,-0.531873,-0.798585,-1.440730,1.621983,0.941412,0.773559,-0.497643,-0.461968
396,-0.856321,-0.705077,-0.662850,-0.408411,1.100822,1.621983,0.941412,0.773559,-0.497643,-0.461968
397,-0.856321,-0.714680,-0.584264,-0.296088,1.391285,1.621983,0.941412,0.773559,-0.497643,-0.461968

In [112]:
y_s

          mpg
0   -0.706439
1   -1.090751
2   -0.706439
3   -0.962647
4   -0.834543
..        ...
393  0.446497
394  2.624265
395  1.087017
396  0.574601
397  0.958913

[398 rows x 1 columns]

In [118]:
x_train, x_test, y_train, y_test = train_test_split(x_s, y_s, test_size=0.2, random_state=0)

In [120]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(318, 10)
(80, 10)
(318, 1)
(80, 1)

In [121]:
len(data)

398

In [122]:
data.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'car_type',
       'origin_America', 'origin_Asia', 'origin_Europe'],
      dtype='str')

In [123]:
regression_model = LinearRegression()
regression_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coef for {} is {}'.format(col_name, regression_model.coef_[0][idx]))
    
print('======')

intercept = regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

print('======')

The coef for cyl is 0.24638776053571687
The coef for disp is 0.29177092098664414
The coef for hp is -0.18081621820393626
The coef for wt is -0.6675530609868126
The coef for acc is 0.06537309205777075
The coef for yr is 0.348177025942672
The coef for car_type is 0.33392312539603647
The coef for origin_America is -0.08117984631927028
The coef for origin_Asia is 0.06986098209664926
The coef for origin_Europe is 0.030003161242288107
======
The intercept is -0.01800683137092325
======

## Ridge Model

In [124]:
ridge_model = Ridge(alpha=0.3)
ridge_model.fit(x_train,y_train)

print('Ridge model coef: {}'.format(ridge_model.coef_))

Ridge model coef: [ 0.24342352  0.28293268 -0.18074242 -0.65967997  0.06398366  0.34745486
  0.33096428 -0.08087356  0.06988696  0.0295866 ]

## Lasso Model

In [126]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)

print('Lasso model coef: {}'.format(lasso_model.coef_))

Lasso model coef: [-0.         -0.         -0.07247557 -0.45867691  0.          0.2698134
  0.11341188 -0.04988145  0.          0.        ]

In [127]:
print(regression_model.score(x_train, y_train))
print(regression_model.score(x_test, y_test))
print('***')
print(ridge_model.score(x_train,y_train))
print(ridge_model.score(x_test,y_test))
print('***')
print(lasso_model.score(x_train,y_train))
print(lasso_model.score(x_test,y_test))

0.8373422857977738
0.8474768646673947
***
0.837332956087454
0.847263786646594
***
0.8007202116330951
0.8283046020148332